doctrine:
    dbal:
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'

            migrations:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            MoneyTransfer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/MoneyTransfer'
                prefix: 'App\MoneyTransfer'
                alias: MoneyTransfer

            Wallet:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/MoneyTransfer/Wallet'
                prefix: 'App\MoneyTransfer\Wallet'
                alias: Wallet

            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/MoneyTransfer/User'
                prefix: 'App\MoneyTransfer\User'
                alias: User
