#!/bin/bash

if command -v google-chrome; then
    google-chrome "http://localhost:8000/"
    google-chrome "http://localhost:8000/swagger/"
else
    if command -v firefox; then
        firefox "http://localhost:8000/"
        firefox "http://localhost:8000/swagger/"
    fi
fi
