#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: '../src/Controller'
    defaults: { _format: json }
    type: annotation
    prefix: /api

api_login_check:
    path: /login_check
